name: Fatfree

on:
  push:
    branches:
      - '*.x'
  pull_request:

jobs:
  latest:
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2', '8.3' ]
    uses: ./.github/workflows/integration.yml
    with:
      php: ${{ matrix.php }}
      suite: Fatfree
      package: f3-factory/fatfree-psr7
